config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: "users/sessions",
                                    registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root "public/pages#top"
  root to: 'public/pages#top'
  get "/", to: "public/pages#top", as: "user_root"
  get "/users/edit",to: "public/pages#top"
  get "/user/edit",to: "public/pages#top"
  get "/user/basic" ,to: "public/pages#top"
  get "/user/new" ,to: "public/pages#top"
  get "/users/edit", to: "public/pages#top"
  get "/user/edit", to: "public/pages#top"
  get "/about", to: "public/pages#top"
  get "/item/new", to: "public/pages#top"
  get "/item/:id", to: "public/pages#top"
  get "/user/:id/items",to: "public/pages#top"
  get "/item/:id/basic", to: "public/pages#top"


  namespace :admin do
    get    "/manual",  to: "pages#manual"


    resources :users do
      member do
        patch :toggle_admin
      end
    end

    resources :items do
      member do
        patch :confirm
        patch :reject
      end
    end

    resources :tags
    resources :usages

  end



  scope module: :public do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
    resources :items do
      resources :chat do
        resources :messages, only: [:create, :update]
      end
    end
    resources :categories, only: [:show],param: :path_name do
      collection do
        get :all
      end
    end
  end

  namespace :api, {format: 'json'} do
    get    "/get_tags", to: "get_tags#index"
    get    "/get_sub_cates", to: "get_sub_cates#index"
    get    "/get_items",     to: "get_items#index"
    get    "/get_items_category", to: "get_items#category"
    get    "/get_state",     to:  "get_state#index"
    get    "/get_current_user", to: "current_user#index"
    put    "/update_current_user", to: "current_user#update"
    get    "/get_item",   to: "get_items#show"
    get    "/check_unique", to: "check_unique#index"
    get    "/check_login",  to: "current_user#check"
    get    "/get_user", to: "get_user#index"
    post   "/create_item",         to: "create_item#index"
    delete "/delete_item", to:"delete_item#index"
  end

end

app/models/item.rb
class Item < ApplicationRecord
  attr_accessor :before_tags
  include TagsHelper
  belongs_to :user
  belongs_to :category
  belongs_to :sub_category ,optional: true

  has_one :building_info, dependent: :destroy
  has_one :food_info, dependent: :destroy
  has_many :item_usages, dependent: :destroy
  has_many :usages, through: :item_usages
  has_many :pictures, dependent: :destroy
  has_many :item_contacts, dependent: :destroy

  has_and_belongs_to_many :tags
  has_many :items_tags, dependent: :destroy

  accepts_nested_attributes_for :building_info, reject_if: :reject_build
  accepts_nested_attributes_for :food_info, reject_if: :reject_food
  accepts_nested_attributes_for :pictures, reject_if: :reject_blank
  accepts_nested_attributes_for :tags, reject_if: :tag_blank

  enum status: {審査中: 0, 公開中: 1, 下書き: 2, 審査落ち:3}


  enum state: {
    北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47
  }

  enum areas: {
    高知市:1, 仁淀川:2, 嶺北:3, 物部川:4, 安芸・室戸:5, 四万十・足摺:6, 高知県外:7
  }

  validates :title, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 40 }

  validates :profile, presence: true, length: { maximum: 800 }
  validates :comment,
            length: { maximum: 800 }
  validates :state,:city,:price,
            presence: true

  validates :is_rent, inclusion: {in: [true, false]}


  # validates :sub_category_id , presence: true, if: :need_sub_categroy



  validate :need_usage
  # validate :need_picture
  validate :check_picture_count


  before_destroy :delete_unuse_tag
  after_destroy :delete_unuse_tag

  before_save :make_path_name

  def category_name
    return unless self.category
    self.category.name
  end

  def sub_category_name
    return  unless self.sub_category
    self.sub_category.name
  end

  def need_food_info?
    return false unless self.category_name
    self.category_name == "廃棄食材"
  end

  def food_info_raw
    food_info.raw
  end

  def food_info_amount
    food_info.amount
  end

  def need_building_info?
    self.category_name == "建物"
  end

  def building_info_about
    building_info.about
  end

  def building_info_status
    building_info.status
  end

  def building_info_price
    building_info.price
  end

  def building_info_rent
    building_info.rent
  end

  # def to_param
  #   id
  # end

  # def find_by!(arg, *args)
  #   where(arg, *args).take!
  # rescue ::RangeError
  #   raise RecordNotFound.new("Couldn't find #{@klass.name} with an out of range value",
  #                            @klass.name)
  # end

  def make_path_name
    self.path_name = ".#{self.title}"
  end

  def need_sub_categroy
    need_sub_cateroy_categories = ["建物", "土地"]

    return need_sub_cateroy_categories.include?(self.category_name)
  end


  private
    def reject_build
      # self.category_name != "建物"
      true
    end

    def reject_blank(attributed)
      attributed['content'].blank?
    end


    def reject_food
      # self.category_name != "廃棄食材"
      true
    end

    def tag_blank(attributed)
      attributed['name'].blank?
    end

    def same_tag(attributed)
    end

    def need_usage
      if self.category_name == "建物"
        errors[:base] << '使用可能用途を一つ以上選択してください' if self.usages.length == 0
      end
    end

    def need_picture
      errors[:base] << '写真は一枚以上必要です' if self.pictures.length == 0
    end

    def check_picture_count
      errors[:base] << '写真は5枚以下にする必要があります' if self.pictures.length >5
    end

    def destroy_items_tags
      ItemsTag.where(item_id: self.id).destroy_all
    end






end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController

  before_action :set_item, only: [:confirm, :reject, :destroy]

  def index
    @items = Item.where(status: 1)
    @wait_items = Item.where(status: 0)
  end

  def new
    return redirect_to edit_user_path(current_user.id) unless current_user.owner
    @item = Item.new
    @item.pictures.build
    3.times{@item.tags.build}
  end

  def create
    @item = Item.new(item_params)
    @item.status = 1
    set_tag
    if @item.save
      redirect_to admin_items_path
    else
      @item.pictures.build
      render 'new'
    end
  end

  def confirm
    @item.update(status: 1, reject_text: nil)
    redirect_to :back
  end

  def reject
    @item.update(status: 3, reject_text: params["item"]["reject_text"])
    redirect_to :back
  end

  def destroy
    @item.destroy
    redirect_to :back
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end
  def item_params
    params.require(:item).permit(
      :title,
      :category_id,
      :profile,
      :remark,
      :state,
      :city,
      :comment,
      :sub_category_id,
      { :usage_ids=> [] },
      building_info_attributes: [:about,:status,:price,:rent],
      food_info_attributes: [:raw, :amount],
      pictures_attributes: [:content, :comment],
      tags_attributes: [:name]
      ).merge(user_id: current_user.id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def full_address(item)
    "#{item.state} #{item.city}"
  end

  def item_main_picutre(item, style = :thumb)
    image_tag(item.pictures.first.content_url(style))
  end

  def rent_type(item)
    if item.building_info_rent
      return "賃貸"
    else
      return "販売"
    end
  end

  def owner?(item)
    return false unless current_user
    current_user.id == item.user.id
  end


end

app/views/admin/items/index.html.haml
資産管理ページ
= link_to "資産を追加する",new_admin_item_path
.waitng-items
  審査待ち資産一覧
  = "(#{@wait_items.length}件)"
  - @wait_items.each do |item|
    .waiting-item
      = link_to item_path(item) do
        = "名前：#{item.title} "
        = item_main_picutre(item)
    - if item.reject_text
      .reject_title
        この資産はユーザーが修正をしました
      .reject_text
        = "前回審査落ち理由: #{item.reject_text}"
    .waiting-bottun
      = link_to "資産削除", admin_item_path(item), method: :delete,data: { confirm: "本当にこの資産を削除しますか？"}
      = link_to "公開中にする", confirm_admin_item_path(item), method: :patch, data: { confirm: "この資産を公開中にしますか？"}
      = form_for item, url: reject_admin_item_path(item) do |f|
        .form_item.need_item
          = f.label :reject_text, "審査落ち理由"
          = f.text_field :reject_text, class: 'form-control'
        = f.submit "公開取り消し(審査落ち)にする",class: "btn btn-primary",data: { confirm: "この資産を審査落ちにしますか？"}

.public-items
  公開中資産一覧
  = "(#{@items.length}件)"
  - @items.each do |item|
    .waiting-item
      = link_to item_path(item) do
        = "名前：#{item.title} "
        = item_main_picutre(item)
    .waiting-bottun
      = link_to "資産削除", admin_item_path(item), method: :delete,data: { confirm: "本当にこの資産を削除しますか？"}
      = form_for item, url: reject_admin_item_path(item) do |f|
        .form_item.need_item
          = f.label :reject_text, "審査落ち理由"
          = f.text_field :reject_text, class: 'form-control'
        = f.submit "公開取り消し(審査落ち)にする",class: "btn btn-primary",data: { confirm: "この資産を審査落ちにしますか？"}

app/views/admin/items/new.html.haml
資産追加

= form_for @item, url: admin_items_path do |f|
  = render 'shared/error_messages', object: f.object

  .form_item.need_item
    = f.label :title, "名称"
    = f.text_field :title, class: 'form-control', required: true

  .form_item.need_item.need_item
    = f.label :category_id, "タイプは?"
    = f.collection_radio_buttons :category_id, Category.all, :id, :name,{},class: "item_category", required: true

  .form_item#sub_category_form.need_item
    - if @item.sub_category
      = f.label :sub_category_ategory, "サブカテゴリーは?"
      = f.collection_radio_buttons :sub_category_id, SubCategory.where(category_id: @item.category.id), :id, :name,{},class: "item_category"



  .form_item.need_item
    = f.label :profile, "説明"
    = f.text_field :profile, class: 'form-control', required: true


  .form_item
  = f.label :remark , "備考"
  = f.text_area :remark

  .form_item.need_item
    = f.label :state, "都道府県"
    = f.select :state, Item.states.keys,{selected: "高知県"}, {class: "select_state"}

  .form_item.need_item
    = f.label :city, "市町村"
    = f.select :city,"aa", {prompt: "市町村を選択してください"}, {class: "select_citys"}

  - unless current_user.owner_category == "オーナー"
    .form_item
      = f.label :comment , "オーナーからのコメント"
      = f.text_area :comment

  .form_item.picture_area
    .picture_field
      = f.fields_for :pictures do |p|
        = p.label :content do
          = image_tag("kesiki.jpg", class: "picture_preview")
        = p.file_field :content, class: "display_none file"
        .picture_comment
          = p.text_field :comment

  .add_picture_bottun
    写真を追加する＋




  .type_form#buiding_info_form.hidden_item
    = f.fields_for :building_info,@item.building_info || @item.build_building_info  do |b|
      .form_item.need_item
        = b.label :about , "建物の状態"
        = b.text_area :about
      .form_item.need_item
        = b.label :status , "建物の特徴"
        = b.text_area :status
      .form_item.need_item
        = b.label :price, "値段"
        = b.text_field :price
      .form_item.need_item
        = b.radio_button :rent, 0, checked: true
        = b.label :rent, "建物を貸し出す", value: 0
        = b.radio_button :rent, 1
        = b.label :rent, "建物を販売する", value: 1
      .form_item.need_item
        使用可能用途
        .c
          = f.collection_check_boxes :usage_ids, Usage.all, :id, :name, include_hidden: false do |b|
            = b.label width: "150px" do
              =b.check_box + b.text

  .type_form#food_info_form.hidden_item
    = f.fields_for :food_info,@item.food_info || @item.build_food_info  do |fo|
      .form_item.need_item
        = fo.label :raw , "原材料"
        = fo.text_area :raw
      .form_item
        = fo.label :amount , "量"
        = fo.text_area :amount

  - 3.times do |n|
    = f.fields_for :tags,@item.tags[n] || @item.tags.build  do |t|
      %span.form_item
        =t.label :name ,"タグ名"
        =t.text_field :name, class: "tag_field"
        .tag_summarys










  .form_item
    = f.submit "資産を登録する", class: "btn btn-primary",data: { confirm: "この資産はすぐに公開中になりますがよろしいですか？"}