config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: "users/sessions",
                                    registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root "public/pages#top"
  root to: 'public/pages#top'
  get "/", to: "public/pages#top", as: "user_root"
  get "/users/edit",to: "public/pages#top"
  get "/user/edit",to: "public/pages#top"
  get "/user/basic" ,to: "public/pages#top"
  get "/user/new" ,to: "public/pages#top"
  get "/users/edit", to: "public/pages#top"
  get "/user/edit", to: "public/pages#top"
  get "/about", to: "public/pages#top"
  get "/item/new", to: "public/pages#top"
  get "/item/:id", to: "public/pages#top"
  get "/user/:id/items",to: "public/pages#top"
  get "/item/:id/basic", to: "public/pages#top"


  namespace :admin do
    get    "/manual",  to: "pages#manual"


    resources :users do
      member do
        patch :toggle_admin
      end
    end

    resources :items do
      member do
        patch :confirm
        patch :reject
      end
    end

    resources :tags
    resources :usages

  end



  scope module: :public do
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
    resources :items do
      resources :chat do
        resources :messages, only: [:create, :update]
      end
    end
    resources :categories, only: [:show],param: :path_name do
      collection do
        get :all
      end
    end
  end

  namespace :api, {format: 'json'} do
    get    "/get_tags", to: "get_tags#index"
    get    "/get_sub_cates", to: "get_sub_cates#index"
    get    "/get_items",     to: "get_items#index"
    get    "/get_items_category", to: "get_items#category"
    get    "/get_state",     to:  "get_state#index"
    get    "/get_current_user", to: "current_user#index"
    put    "/update_current_user", to: "current_user#update"
    get    "/get_item",   to: "get_items#show"
    get    "/check_unique", to: "check_unique#index"
    get    "/check_login",  to: "current_user#check"
    get    "/get_user", to: "get_user#index"
    post   "/create_item",         to: "create_item#index"
    delete "/delete_item", to:"delete_item#index"
  end

end

app/views/layouts/_alert.html.haml
- flash.each do |message_type, message|
  %div{:class => "flash flash-#{message_type}"}
    = message
    %span.flash-delete-button
      ×

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{ name: 'viewport', content: 'initial-scale=1.0, user-scalable=no' }
    %title Vacant
    = favicon_link_tag('favicon.ico')
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -# - if admin_user?
    -#     .admin_hedder
    -#       管理者用ヘッダー
    -#       =link_to "ユーザー管理", admin_users_path
    -#       = link_to "資産管理", admin_items_path
    -#       = link_to "使用可能用途一覧", admin_usages_path
    -#       = link_to "タグ管理",admin_tags_path
    -#       = link_to "マニュアル", admin_manual_path
    -# .header
    -#   %navbar
    -#     = link_to "トップページへ", root_path
    -#     - if current_user
    -#       = image_tag(set_avatar(current_user, :thumb), class: "avatar_thumb")
    -#       = full_name(current_user)
    -#       = link_to "ログアウト", logout_path, method: :delete
    -#       = link_to "ユーザー設定へ", edit_user_path(current_user)
    -#       - if  current_user.items == []
    -#         = link_to "資産を登録する", new_item_path
    -#       -else
    -#         = link_to "資産を管理する", items_path

    -#       -if  current_user.yet_look_message_items != [] || current_user.reject_items != []
    -#         .noti_title
    -#           お知らせがあります
    -#         -if  current_user.yet_look_message_items != []
    -#           .contact_for_item
    -#             資産に対する問い合わせが来てます
    -#           -current_user.yet_look_message_items.each do |item|
    -#             = link_to item_path(item) do
    -#               =item.title

    -#         -if current_user.reject_items != []
    -#           .reject_items
    -#             審査落ちした資産があります
    -#           - current_user.reject_items.each do |item|
    -#             = link_to item_path(item) do
    -#               =item.title



    -#     - else
    -#       = link_to "新規登録", new_user_path
    -#       = link_to "ログイン", login_path

    = render 'layouts/alert'
    = yield

    = stylesheet_pack_tag 'app_vue'

-# !!!
-# %html
-#   %head
-#     %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
-#     %title ChatSpace
-#     = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
-#     = javascript_include_tag 'application', 'data-turbolinks-track' => true
-#     = csrf_meta_tags
-#   %body
-#     = yield